// Generated by tools/assets/gen_sounds.py - do not edit.
#pragma once

namespace mcs
{
enum Sound : int
{
	MCS_XP_ORB, // entity.experience_orb.pickup
	MCS_LEVELUP, // entity.player.levelup
	MCS_ATTACK_STRONG, // entity.player.attack.strong
	MCS_ATTACK_SWEEP, // entity.player.attack.sweep
	MCS_ATTACK_CRIT, // entity.player.attack.crit
	MCS_ATTACK_KNOCKBACK, // entity.player.attack.knockback
	MCS_ATTACK_WEAK, // entity.player.attack.weak
	MCS_ATTACK_NODAMAGE, // entity.player.attack.nodamage
	MCS_PLAYER_HURT, // entity.player.hurt
	MCS_PLAYER_DEATH, // entity.player.death
	MCS_PLAYER_SMALL_FALL, // entity.player.small_fall
	MCS_PLAYER_BIG_FALL, // entity.player.big_fall
	MCS_PLAYER_BURP, // entity.player.burp
	MCS_GENERIC_EAT, // entity.generic.eat
	MCS_EQUIP_DIAMOND, // item.armor.equip_diamond
	MCS_EQUIP_ELYTRA, // item.armor.equip_elytra
	MCS_EQUIP_GENERIC, // item.armor.equip_generic
	MCS_ELYTRA_FLYING, // item.elytra.flying
	MCS_FIREWORK_LAUNCH, // entity.firework_rocket.launch
	MCS_FIREWORK_BLAST, // entity.firework_rocket.blast
	MCS_FIREWORK_LARGE_BLAST, // entity.firework_rocket.large_blast
	MCS_FIREWORK_TWINKLE, // entity.firework_rocket.twinkle
	MCS_ITEM_PICKUP, // entity.item.pickup
	MCS_ITEM_BREAK, // entity.item.break
	MCS_TOTEM_USE, // item.totem.use
	MCS_ARROW_SHOOT, // entity.arrow.shoot
	MCS_ARROW_HIT, // entity.arrow.hit
	MCS_ARROW_HIT_PLAYER, // entity.arrow.hit_player
	MCS_BOW_PULL, // item.crossbow.loading_middle
	MCS_EXPLODE, // entity.generic.explode
	MCS_TNT_PRIMED, // entity.tnt.primed
	MCS_ZOMBIE_HURT, // entity.zombie.hurt
	MCS_ZOMBIE_DEATH, // entity.zombie.death
	MCS_UI_CLICK, // ui.button.click
	MCS_THUNDER, // entity.lightning_bolt.thunder
	MCS_DOOR_WOOD_OPEN, // block.wooden_door.open
	MCS_DOOR_WOOD_CLOSE, // block.wooden_door.close
	MCS_DOOR_IRON_OPEN, // block.iron_door.open
	MCS_DOOR_IRON_CLOSE, // block.iron_door.close
	MCS_CHEST_OPEN, // block.chest.open
	MCS_NOTE_PLING, // block.note_block.pling
	MCS_ANVIL_LAND, // block.anvil.land
	MCS_CREEPER_PRIMED, // entity.creeper.primed
	MCS_CREEPER_HURT, // entity.creeper.hurt
	MCS_CREEPER_DEATH, // entity.creeper.death
	MCS_HUSK_HURT, // entity.husk.hurt
	MCS_HUSK_DEATH, // entity.husk.death
	MCS_DROWNED_HURT, // entity.drowned.hurt
	MCS_DROWNED_DEATH, // entity.drowned.death
	MCS_TOAST_IN, // ui.toast.in
	MCS_TOAST_CHALLENGE, // ui.toast.challenge_complete
	MCS_ENDERMAN_HURT, // entity.enderman.hurt
	MCS_ENDERMAN_DEATH, // entity.enderman.death
	MCS_ENDERMAN_TELEPORT, // entity.enderman.teleport
	MCS_ENDERMAN_STARE, // entity.enderman.stare
	MCS_LEVER_CLICK, // block.lever.click
	MCS_STONE_BUTTON_ON, // block.stone_button.click_on
	MCS_STONE_BUTTON_OFF, // block.stone_button.click_off
	MCS_WOOD_BUTTON_ON, // block.wooden_button.click_on
	MCS_WOOD_BUTTON_OFF, // block.wooden_button.click_off
	MCS_STONE_PLATE_ON, // block.stone_pressure_plate.click_on
	MCS_STONE_PLATE_OFF, // block.stone_pressure_plate.click_off
	MCS_WOOD_PLATE_ON, // block.wooden_pressure_plate.click_on
	MCS_WOOD_PLATE_OFF, // block.wooden_pressure_plate.click_off
	MCS_CROSSBOW_LOAD_START, // item.crossbow.loading_start
	MCS_CROSSBOW_LOAD_END, // item.crossbow.loading_end
	MCS_CROSSBOW_SHOOT, // item.crossbow.shoot
	MCS_FLINT_USE, // item.flintandsteel.use
	MCS_FIRE_AMBIENT, // block.fire.ambient
	MCS_PLAYER_HURT_FIRE, // entity.player.hurt_on_fire
	MCS_ENCHANT, // block.enchantment_table.use
	MCS_IRON_GOLEM_ATTACK, // entity.iron_golem.attack
	MCS_IRON_GOLEM_HURT, // entity.iron_golem.hurt
	MCS_IRON_GOLEM_DEATH, // entity.iron_golem.death
	MCS_IRON_GOLEM_STEP, // entity.iron_golem.step
	MCS_WITHER_SPAWN, // entity.wither.spawn
	MCS_WITHER_AMBIENT, // entity.wither.ambient
	MCS_WITHER_SHOOT, // entity.wither.shoot
	MCS_WITHER_HURT, // entity.wither.hurt
	MCS_WITHER_DEATH, // entity.wither.death
	MCS_WITHER_BREAK_BLOCK, // entity.wither.break_block
	MCS_STONE_BREAK, // block.stone.break
	MCS_STONE_HIT, // block.stone.hit
	MCS_STONE_PLACE, // block.stone.place
	MCS_STONE_STEP, // block.stone.step
	MCS_WOOD_BREAK, // block.wood.break
	MCS_WOOD_HIT, // block.wood.hit
	MCS_WOOD_PLACE, // block.wood.place
	MCS_WOOD_STEP, // block.wood.step
	MCS_SAND_BREAK, // block.sand.break
	MCS_SAND_HIT, // block.sand.hit
	MCS_SAND_PLACE, // block.sand.place
	MCS_SAND_STEP, // block.sand.step
	MCS_GRAVEL_BREAK, // block.gravel.break
	MCS_GRAVEL_HIT, // block.gravel.hit
	MCS_GRAVEL_PLACE, // block.gravel.place
	MCS_GRAVEL_STEP, // block.gravel.step
	MCS_GRASS_BREAK, // block.grass.break
	MCS_GRASS_HIT, // block.grass.hit
	MCS_GRASS_PLACE, // block.grass.place
	MCS_GRASS_STEP, // block.grass.step
	MCS_GLASS_BREAK, // block.glass.break
	MCS_GLASS_HIT, // block.glass.hit
	MCS_GLASS_PLACE, // block.glass.place
	MCS_GLASS_STEP, // block.glass.step
	MCS_METAL_BREAK, // block.metal.break
	MCS_METAL_HIT, // block.metal.hit
	MCS_METAL_PLACE, // block.metal.place
	MCS_METAL_STEP, // block.metal.step
	MCS_WOOL_BREAK, // block.wool.break
	MCS_WOOL_HIT, // block.wool.hit
	MCS_WOOL_PLACE, // block.wool.place
	MCS_WOOL_STEP, // block.wool.step
	MCS_COUNT
};

struct SoundVariant
{
	const char* file; // relative to sound/
	float volume;
	float pitch;
	int weight;
};

struct SoundEvent
{
	const char* event;
	int numVariants;
	const SoundVariant* variants;
};

extern const SoundEvent g_sounds[MCS_COUNT];
// First block sound group entry; group g kind k (0 break,1 hit,2 place,3 step) = base + g*4 + k
static const int MCS_BLOCK_BASE = MCS_STONE_BREAK;
} // namespace mcs
