// Generated by tools/assets/gen_sounds.py - do not edit.
#include "mc_sounds_gen.h"

namespace mcs
{
static const SoundVariant v_XP_ORB[] = {{"mc/random/orb.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_LEVELUP[] = {{"mc/random/levelup.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ATTACK_STRONG[] = {{"mc/entity/player/attack/strong1.wav", 0.600f, 1.000f, 1}, {"mc/entity/player/attack/strong2.wav", 0.600f, 1.000f, 1}, {"mc/entity/player/attack/strong3.wav", 0.600f, 1.000f, 1}, {"mc/entity/player/attack/strong4.wav", 0.600f, 1.000f, 1}, {"mc/entity/player/attack/strong5.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/strong6.wav", 0.700f, 1.000f, 1}};
static const SoundVariant v_ATTACK_SWEEP[] = {{"mc/entity/player/attack/sweep1.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/sweep2.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/sweep3.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/sweep4.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/sweep5.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/sweep6.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/sweep7.wav", 0.700f, 1.000f, 1}};
static const SoundVariant v_ATTACK_CRIT[] = {{"mc/entity/player/attack/crit1.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/crit2.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/crit3.wav", 0.700f, 1.000f, 1}};
static const SoundVariant v_ATTACK_KNOCKBACK[] = {{"mc/entity/player/attack/knockback1.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/knockback2.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/knockback3.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/knockback4.wav", 0.700f, 1.000f, 1}};
static const SoundVariant v_ATTACK_WEAK[] = {{"mc/entity/player/attack/weak1.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/weak2.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/weak3.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/weak4.wav", 0.700f, 1.000f, 1}};
static const SoundVariant v_ATTACK_NODAMAGE[] = {{"mc/entity/player/attack/weak1.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/weak2.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/weak3.wav", 0.700f, 1.000f, 1}, {"mc/entity/player/attack/weak4.wav", 0.700f, 1.000f, 1}};
static const SoundVariant v_PLAYER_HURT[] = {{"mc/damage/hit1.wav", 1.000f, 1.000f, 1}, {"mc/damage/hit2.wav", 1.000f, 1.000f, 1}, {"mc/damage/hit3.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_PLAYER_DEATH[] = {{"mc/damage/hit1.wav", 1.000f, 1.000f, 1}, {"mc/damage/hit2.wav", 1.000f, 1.000f, 1}, {"mc/damage/hit3.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_PLAYER_SMALL_FALL[] = {{"mc/damage/fallsmall.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_PLAYER_BIG_FALL[] = {{"mc/damage/fallbig.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_PLAYER_BURP[] = {{"mc/random/burp.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GENERIC_EAT[] = {{"mc/random/eat1.wav", 1.000f, 1.000f, 1}, {"mc/random/eat2.wav", 1.000f, 1.000f, 1}, {"mc/random/eat3.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_EQUIP_DIAMOND[] = {{"mc/item/armor/equip_diamond1.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_diamond2.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_diamond3.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_diamond4.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_diamond5.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_diamond6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_EQUIP_ELYTRA[] = {{"mc/item/armor/equip_leather1.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_leather2.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_leather3.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_leather4.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_leather5.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_leather6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_EQUIP_GENERIC[] = {{"mc/item/armor/equip_generic1.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_generic2.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_generic3.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_generic4.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_generic5.wav", 1.000f, 1.000f, 1}, {"mc/item/armor/equip_generic6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ELYTRA_FLYING[] = {{"mc/item/elytra/elytra_loop.wav", 0.600f, 1.000f, 1}};
static const SoundVariant v_FIREWORK_LAUNCH[] = {{"mc/fireworks/launch1.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_FIREWORK_BLAST[] = {{"mc/fireworks/blast1.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_FIREWORK_LARGE_BLAST[] = {{"mc/fireworks/largeblast1.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_FIREWORK_TWINKLE[] = {{"mc/fireworks/twinkle1.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ITEM_PICKUP[] = {{"mc/random/pop.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ITEM_BREAK[] = {{"mc/random/break.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_TOTEM_USE[] = {{"mc/item/totem/use_totem.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ARROW_SHOOT[] = {{"mc/random/bow.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ARROW_HIT[] = {{"mc/random/bowhit1.wav", 1.000f, 1.000f, 1}, {"mc/random/bowhit2.wav", 1.000f, 1.000f, 1}, {"mc/random/bowhit3.wav", 1.000f, 1.000f, 1}, {"mc/random/bowhit4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ARROW_HIT_PLAYER[] = {{"mc/random/successful_hit.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_BOW_PULL[] = {{"mc/item/crossbow/loading_middle1.wav", 0.650f, 1.000f, 1}, {"mc/item/crossbow/loading_middle1.wav", 0.650f, 0.950f, 1}, {"mc/item/crossbow/loading_middle1.wav", 0.650f, 1.200f, 1}, {"mc/item/crossbow/loading_middle2.wav", 0.650f, 1.000f, 1}, {"mc/item/crossbow/loading_middle2.wav", 0.650f, 0.900f, 1}, {"mc/item/crossbow/loading_middle2.wav", 0.650f, 1.050f, 1}, {"mc/item/crossbow/loading_middle3.wav", 0.650f, 1.000f, 1}, {"mc/item/crossbow/loading_middle3.wav", 0.650f, 0.900f, 1}, {"mc/item/crossbow/loading_middle3.wav", 0.650f, 1.050f, 1}, {"mc/item/crossbow/loading_middle4.wav", 0.650f, 1.000f, 1}};
static const SoundVariant v_EXPLODE[] = {{"mc/random/explode1.wav", 1.000f, 1.000f, 1}, {"mc/random/explode2.wav", 1.000f, 1.000f, 1}, {"mc/random/explode3.wav", 1.000f, 1.000f, 1}, {"mc/random/explode4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_TNT_PRIMED[] = {{"mc/random/fuse.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ZOMBIE_HURT[] = {{"mc/mob/zombie/hurt1.wav", 1.000f, 1.000f, 1}, {"mc/mob/zombie/hurt2.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ZOMBIE_DEATH[] = {{"mc/mob/zombie/death.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_UI_CLICK[] = {{"mc/random/click_stereo.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_THUNDER[] = {{"mc/ambient/weather/thunder1.wav", 1.000f, 1.000f, 1}, {"mc/ambient/weather/thunder2.wav", 1.000f, 1.000f, 1}, {"mc/ambient/weather/thunder3.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_DOOR_WOOD_OPEN[] = {{"mc/block/wooden_door/open1.wav", 0.900f, 1.000f, 1}, {"mc/block/wooden_door/open2.wav", 0.900f, 1.000f, 1}};
static const SoundVariant v_DOOR_WOOD_CLOSE[] = {{"mc/block/wooden_door/close1.wav", 0.900f, 1.000f, 1}, {"mc/block/wooden_door/close2.wav", 0.900f, 1.000f, 1}, {"mc/block/wooden_door/close3.wav", 0.900f, 1.000f, 1}};
static const SoundVariant v_DOOR_IRON_OPEN[] = {{"mc/block/iron_door/open1.wav", 0.900f, 1.000f, 1}, {"mc/block/iron_door/open2.wav", 0.900f, 1.000f, 1}, {"mc/block/iron_door/open3.wav", 0.900f, 1.000f, 1}, {"mc/block/iron_door/open4.wav", 0.900f, 1.000f, 1}};
static const SoundVariant v_DOOR_IRON_CLOSE[] = {{"mc/block/iron_door/close1.wav", 0.900f, 1.000f, 1}, {"mc/block/iron_door/close2.wav", 0.900f, 1.000f, 1}, {"mc/block/iron_door/close3.wav", 0.900f, 1.000f, 1}, {"mc/block/iron_door/close4.wav", 0.900f, 1.000f, 1}};
static const SoundVariant v_CHEST_OPEN[] = {{"mc/block/chest/open.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_NOTE_PLING[] = {{"mc/note/pling.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ANVIL_LAND[] = {{"mc/random/anvil_land.wav", 0.500f, 1.000f, 1}};
static const SoundVariant v_CREEPER_PRIMED[] = {{"mc/random/fuse.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_CREEPER_HURT[] = {{"mc/mob/creeper/say1.wav", 1.000f, 1.000f, 1}, {"mc/mob/creeper/say2.wav", 1.000f, 1.000f, 1}, {"mc/mob/creeper/say3.wav", 1.000f, 1.000f, 1}, {"mc/mob/creeper/say4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_CREEPER_DEATH[] = {{"mc/mob/creeper/death.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_HUSK_HURT[] = {{"mc/mob/husk/hurt1.wav", 1.000f, 1.000f, 1}, {"mc/mob/husk/hurt2.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_HUSK_DEATH[] = {{"mc/mob/husk/death1.wav", 1.000f, 1.000f, 1}, {"mc/mob/husk/death2.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_DROWNED_HURT[] = {{"mc/mob/drowned/hurt1.wav", 0.900f, 1.000f, 1}, {"mc/mob/drowned/hurt2.wav", 0.900f, 1.000f, 1}, {"mc/mob/drowned/hurt3.wav", 0.900f, 1.000f, 1}};
static const SoundVariant v_DROWNED_DEATH[] = {{"mc/mob/drowned/death1.wav", 0.900f, 1.000f, 1}, {"mc/mob/drowned/death2.wav", 0.900f, 1.000f, 1}};
static const SoundVariant v_TOAST_IN[] = {{"mc/ui/toast/in.wav", 0.400f, 1.000f, 1}};
static const SoundVariant v_TOAST_CHALLENGE[] = {{"mc/ui/toast/challenge_complete.wav", 0.600f, 1.000f, 1}};
static const SoundVariant v_ENDERMAN_HURT[] = {{"mc/mob/endermen/hit1.wav", 1.000f, 1.000f, 1}, {"mc/mob/endermen/hit2.wav", 1.000f, 1.000f, 1}, {"mc/mob/endermen/hit3.wav", 1.000f, 1.000f, 1}, {"mc/mob/endermen/hit4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ENDERMAN_DEATH[] = {{"mc/mob/endermen/death.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ENDERMAN_TELEPORT[] = {{"mc/mob/endermen/portal.wav", 1.000f, 1.000f, 1}, {"mc/mob/endermen/portal2.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ENDERMAN_STARE[] = {{"mc/mob/endermen/stare.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_LEVER_CLICK[] = {{"mc/random/click.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_STONE_BUTTON_ON[] = {{"mc/random/click.wav", 0.300f, 0.600f, 1}};
static const SoundVariant v_STONE_BUTTON_OFF[] = {{"mc/random/click.wav", 0.300f, 0.500f, 1}};
static const SoundVariant v_WOOD_BUTTON_ON[] = {{"mc/random/wood_click.wav", 0.300f, 0.600f, 1}};
static const SoundVariant v_WOOD_BUTTON_OFF[] = {{"mc/random/wood_click.wav", 0.300f, 0.500f, 1}};
static const SoundVariant v_STONE_PLATE_ON[] = {{"mc/random/click.wav", 0.300f, 0.600f, 1}};
static const SoundVariant v_STONE_PLATE_OFF[] = {{"mc/random/click.wav", 0.300f, 0.500f, 1}};
static const SoundVariant v_WOOD_PLATE_ON[] = {{"mc/random/click.wav", 0.300f, 0.800f, 1}};
static const SoundVariant v_WOOD_PLATE_OFF[] = {{"mc/random/click.wav", 0.300f, 0.700f, 1}};
static const SoundVariant v_CROSSBOW_LOAD_START[] = {{"mc/item/crossbow/loading_start.wav", 0.300f, 1.000f, 1}};
static const SoundVariant v_CROSSBOW_LOAD_END[] = {{"mc/item/crossbow/loading_end.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_CROSSBOW_SHOOT[] = {{"mc/item/crossbow/shoot1.wav", 0.800f, 1.000f, 1}, {"mc/item/crossbow/shoot1.wav", 0.900f, 1.000f, 1}, {"mc/item/crossbow/shoot1.wav", 0.900f, 0.900f, 1}, {"mc/item/crossbow/shoot2.wav", 0.800f, 1.000f, 1}, {"mc/item/crossbow/shoot2.wav", 0.900f, 1.000f, 1}, {"mc/item/crossbow/shoot2.wav", 0.900f, 0.900f, 1}, {"mc/item/crossbow/shoot3.wav", 0.800f, 1.000f, 1}, {"mc/item/crossbow/shoot3.wav", 0.900f, 1.000f, 1}, {"mc/item/crossbow/shoot3.wav", 0.900f, 0.900f, 1}};
static const SoundVariant v_FLINT_USE[] = {{"mc/fire/ignite.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_FIRE_AMBIENT[] = {{"mc/fire/fire.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_PLAYER_HURT_FIRE[] = {{"mc/entity/player/hurt/fire_hurt1.wav", 1.000f, 1.000f, 1}, {"mc/entity/player/hurt/fire_hurt2.wav", 1.000f, 1.000f, 1}, {"mc/entity/player/hurt/fire_hurt3.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_ENCHANT[] = {{"mc/block/enchantment_table/enchant1.wav", 1.000f, 1.000f, 1}, {"mc/block/enchantment_table/enchant2.wav", 1.000f, 1.000f, 1}, {"mc/block/enchantment_table/enchant3.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_IRON_GOLEM_ATTACK[] = {{"mc/mob/irongolem/throw.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_IRON_GOLEM_HURT[] = {{"mc/mob/irongolem/hit1.wav", 1.000f, 1.000f, 1}, {"mc/mob/irongolem/hit2.wav", 1.000f, 1.000f, 1}, {"mc/mob/irongolem/hit3.wav", 1.000f, 1.000f, 1}, {"mc/mob/irongolem/hit4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_IRON_GOLEM_DEATH[] = {{"mc/mob/irongolem/death.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_IRON_GOLEM_STEP[] = {{"mc/mob/irongolem/walk1.wav", 1.000f, 1.000f, 1}, {"mc/mob/irongolem/walk2.wav", 1.000f, 1.000f, 1}, {"mc/mob/irongolem/walk3.wav", 1.000f, 1.000f, 1}, {"mc/mob/irongolem/walk4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WITHER_SPAWN[] = {{"mc/mob/wither/spawn.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WITHER_AMBIENT[] = {{"mc/mob/wither/idle1.wav", 1.000f, 1.000f, 1}, {"mc/mob/wither/idle2.wav", 1.000f, 1.000f, 1}, {"mc/mob/wither/idle3.wav", 1.000f, 1.000f, 1}, {"mc/mob/wither/idle4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WITHER_SHOOT[] = {{"mc/mob/wither/shoot.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WITHER_HURT[] = {{"mc/mob/wither/hurt1.wav", 1.000f, 1.000f, 1}, {"mc/mob/wither/hurt2.wav", 1.000f, 1.000f, 1}, {"mc/mob/wither/hurt3.wav", 1.000f, 1.000f, 1}, {"mc/mob/wither/hurt4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WITHER_DEATH[] = {{"mc/mob/wither/death.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WITHER_BREAK_BLOCK[] = {{"mc/mob/zombie/woodbreak.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_STONE_BREAK[] = {{"mc/dig/stone1.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone2.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone3.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_STONE_HIT[] = {{"mc/step/stone1.wav", 1.000f, 1.000f, 1}, {"mc/step/stone2.wav", 1.000f, 1.000f, 1}, {"mc/step/stone3.wav", 1.000f, 1.000f, 1}, {"mc/step/stone4.wav", 1.000f, 1.000f, 1}, {"mc/step/stone5.wav", 1.000f, 1.000f, 1}, {"mc/step/stone6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_STONE_PLACE[] = {{"mc/dig/stone1.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone2.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone3.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_STONE_STEP[] = {{"mc/step/stone1.wav", 1.000f, 1.000f, 1}, {"mc/step/stone2.wav", 1.000f, 1.000f, 1}, {"mc/step/stone3.wav", 1.000f, 1.000f, 1}, {"mc/step/stone4.wav", 1.000f, 1.000f, 1}, {"mc/step/stone5.wav", 1.000f, 1.000f, 1}, {"mc/step/stone6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WOOD_BREAK[] = {{"mc/dig/wood1.wav", 1.000f, 1.000f, 1}, {"mc/dig/wood2.wav", 1.000f, 1.000f, 1}, {"mc/dig/wood3.wav", 1.000f, 1.000f, 1}, {"mc/dig/wood4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WOOD_HIT[] = {{"mc/step/wood1.wav", 1.000f, 1.000f, 1}, {"mc/step/wood2.wav", 1.000f, 1.000f, 1}, {"mc/step/wood3.wav", 1.000f, 1.000f, 1}, {"mc/step/wood4.wav", 1.000f, 1.000f, 1}, {"mc/step/wood5.wav", 1.000f, 1.000f, 1}, {"mc/step/wood6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WOOD_PLACE[] = {{"mc/dig/wood1.wav", 1.000f, 1.000f, 1}, {"mc/dig/wood2.wav", 1.000f, 1.000f, 1}, {"mc/dig/wood3.wav", 1.000f, 1.000f, 1}, {"mc/dig/wood4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WOOD_STEP[] = {{"mc/step/wood1.wav", 1.000f, 1.000f, 1}, {"mc/step/wood2.wav", 1.000f, 1.000f, 1}, {"mc/step/wood3.wav", 1.000f, 1.000f, 1}, {"mc/step/wood4.wav", 1.000f, 1.000f, 1}, {"mc/step/wood5.wav", 1.000f, 1.000f, 1}, {"mc/step/wood6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_SAND_BREAK[] = {{"mc/dig/sand1.wav", 1.000f, 1.000f, 1}, {"mc/dig/sand2.wav", 1.000f, 1.000f, 1}, {"mc/dig/sand3.wav", 1.000f, 1.000f, 1}, {"mc/dig/sand4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_SAND_HIT[] = {{"mc/step/sand1.wav", 1.000f, 1.000f, 1}, {"mc/step/sand2.wav", 1.000f, 1.000f, 1}, {"mc/step/sand3.wav", 1.000f, 1.000f, 1}, {"mc/step/sand4.wav", 1.000f, 1.000f, 1}, {"mc/step/sand5.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_SAND_PLACE[] = {{"mc/dig/sand1.wav", 1.000f, 1.000f, 1}, {"mc/dig/sand2.wav", 1.000f, 1.000f, 1}, {"mc/dig/sand3.wav", 1.000f, 1.000f, 1}, {"mc/dig/sand4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_SAND_STEP[] = {{"mc/step/sand1.wav", 1.000f, 1.000f, 1}, {"mc/step/sand2.wav", 1.000f, 1.000f, 1}, {"mc/step/sand3.wav", 1.000f, 1.000f, 1}, {"mc/step/sand4.wav", 1.000f, 1.000f, 1}, {"mc/step/sand5.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GRAVEL_BREAK[] = {{"mc/dig/gravel1.wav", 1.000f, 1.000f, 1}, {"mc/dig/gravel2.wav", 1.000f, 1.000f, 1}, {"mc/dig/gravel3.wav", 1.000f, 1.000f, 1}, {"mc/dig/gravel4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GRAVEL_HIT[] = {{"mc/step/gravel1.wav", 1.000f, 1.000f, 1}, {"mc/step/gravel2.wav", 1.000f, 1.000f, 1}, {"mc/step/gravel3.wav", 1.000f, 1.000f, 1}, {"mc/step/gravel4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GRAVEL_PLACE[] = {{"mc/dig/gravel1.wav", 1.000f, 1.000f, 1}, {"mc/dig/gravel2.wav", 1.000f, 1.000f, 1}, {"mc/dig/gravel3.wav", 1.000f, 1.000f, 1}, {"mc/dig/gravel4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GRAVEL_STEP[] = {{"mc/step/gravel1.wav", 1.000f, 1.000f, 1}, {"mc/step/gravel2.wav", 1.000f, 1.000f, 1}, {"mc/step/gravel3.wav", 1.000f, 1.000f, 1}, {"mc/step/gravel4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GRASS_BREAK[] = {{"mc/dig/grass1.wav", 1.000f, 1.000f, 1}, {"mc/dig/grass2.wav", 1.000f, 1.000f, 1}, {"mc/dig/grass3.wav", 1.000f, 1.000f, 1}, {"mc/dig/grass4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GRASS_HIT[] = {{"mc/step/grass1.wav", 1.000f, 1.000f, 1}, {"mc/step/grass2.wav", 1.000f, 1.000f, 1}, {"mc/step/grass3.wav", 1.000f, 1.000f, 1}, {"mc/step/grass4.wav", 1.000f, 1.000f, 1}, {"mc/step/grass5.wav", 1.000f, 1.000f, 1}, {"mc/step/grass6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GRASS_PLACE[] = {{"mc/dig/grass1.wav", 1.000f, 1.000f, 1}, {"mc/dig/grass2.wav", 1.000f, 1.000f, 1}, {"mc/dig/grass3.wav", 1.000f, 1.000f, 1}, {"mc/dig/grass4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GRASS_STEP[] = {{"mc/step/grass1.wav", 1.000f, 1.000f, 1}, {"mc/step/grass2.wav", 1.000f, 1.000f, 1}, {"mc/step/grass3.wav", 1.000f, 1.000f, 1}, {"mc/step/grass4.wav", 1.000f, 1.000f, 1}, {"mc/step/grass5.wav", 1.000f, 1.000f, 1}, {"mc/step/grass6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GLASS_BREAK[] = {{"mc/random/glass1.wav", 1.000f, 1.000f, 1}, {"mc/random/glass2.wav", 1.000f, 1.000f, 1}, {"mc/random/glass3.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GLASS_HIT[] = {{"mc/step/stone1.wav", 1.000f, 1.000f, 1}, {"mc/step/stone2.wav", 1.000f, 1.000f, 1}, {"mc/step/stone3.wav", 1.000f, 1.000f, 1}, {"mc/step/stone4.wav", 1.000f, 1.000f, 1}, {"mc/step/stone5.wav", 1.000f, 1.000f, 1}, {"mc/step/stone6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GLASS_PLACE[] = {{"mc/dig/stone1.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone2.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone3.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_GLASS_STEP[] = {{"mc/step/stone1.wav", 1.000f, 1.000f, 1}, {"mc/step/stone2.wav", 1.000f, 1.000f, 1}, {"mc/step/stone3.wav", 1.000f, 1.000f, 1}, {"mc/step/stone4.wav", 1.000f, 1.000f, 1}, {"mc/step/stone5.wav", 1.000f, 1.000f, 1}, {"mc/step/stone6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_METAL_BREAK[] = {{"mc/dig/stone1.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone2.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone3.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_METAL_HIT[] = {{"mc/step/stone1.wav", 1.000f, 1.000f, 1}, {"mc/step/stone2.wav", 1.000f, 1.000f, 1}, {"mc/step/stone3.wav", 1.000f, 1.000f, 1}, {"mc/step/stone4.wav", 1.000f, 1.000f, 1}, {"mc/step/stone5.wav", 1.000f, 1.000f, 1}, {"mc/step/stone6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_METAL_PLACE[] = {{"mc/dig/stone1.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone2.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone3.wav", 1.000f, 1.000f, 1}, {"mc/dig/stone4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_METAL_STEP[] = {{"mc/step/stone1.wav", 1.000f, 1.000f, 1}, {"mc/step/stone2.wav", 1.000f, 1.000f, 1}, {"mc/step/stone3.wav", 1.000f, 1.000f, 1}, {"mc/step/stone4.wav", 1.000f, 1.000f, 1}, {"mc/step/stone5.wav", 1.000f, 1.000f, 1}, {"mc/step/stone6.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WOOL_BREAK[] = {{"mc/dig/cloth1.wav", 1.000f, 1.000f, 1}, {"mc/dig/cloth2.wav", 1.000f, 1.000f, 1}, {"mc/dig/cloth3.wav", 1.000f, 1.000f, 1}, {"mc/dig/cloth4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WOOL_HIT[] = {{"mc/step/cloth1.wav", 1.000f, 1.000f, 1}, {"mc/step/cloth2.wav", 1.000f, 1.000f, 1}, {"mc/step/cloth3.wav", 1.000f, 1.000f, 1}, {"mc/step/cloth4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WOOL_PLACE[] = {{"mc/dig/cloth1.wav", 1.000f, 1.000f, 1}, {"mc/dig/cloth2.wav", 1.000f, 1.000f, 1}, {"mc/dig/cloth3.wav", 1.000f, 1.000f, 1}, {"mc/dig/cloth4.wav", 1.000f, 1.000f, 1}};
static const SoundVariant v_WOOL_STEP[] = {{"mc/step/cloth1.wav", 1.000f, 1.000f, 1}, {"mc/step/cloth2.wav", 1.000f, 1.000f, 1}, {"mc/step/cloth3.wav", 1.000f, 1.000f, 1}, {"mc/step/cloth4.wav", 1.000f, 1.000f, 1}};

const SoundEvent g_sounds[MCS_COUNT] = {
	{"entity.experience_orb.pickup", 1, v_XP_ORB},
	{"entity.player.levelup", 1, v_LEVELUP},
	{"entity.player.attack.strong", 6, v_ATTACK_STRONG},
	{"entity.player.attack.sweep", 7, v_ATTACK_SWEEP},
	{"entity.player.attack.crit", 3, v_ATTACK_CRIT},
	{"entity.player.attack.knockback", 4, v_ATTACK_KNOCKBACK},
	{"entity.player.attack.weak", 4, v_ATTACK_WEAK},
	{"entity.player.attack.nodamage", 4, v_ATTACK_NODAMAGE},
	{"entity.player.hurt", 3, v_PLAYER_HURT},
	{"entity.player.death", 3, v_PLAYER_DEATH},
	{"entity.player.small_fall", 1, v_PLAYER_SMALL_FALL},
	{"entity.player.big_fall", 1, v_PLAYER_BIG_FALL},
	{"entity.player.burp", 1, v_PLAYER_BURP},
	{"entity.generic.eat", 3, v_GENERIC_EAT},
	{"item.armor.equip_diamond", 6, v_EQUIP_DIAMOND},
	{"item.armor.equip_elytra", 6, v_EQUIP_ELYTRA},
	{"item.armor.equip_generic", 6, v_EQUIP_GENERIC},
	{"item.elytra.flying", 1, v_ELYTRA_FLYING},
	{"entity.firework_rocket.launch", 1, v_FIREWORK_LAUNCH},
	{"entity.firework_rocket.blast", 1, v_FIREWORK_BLAST},
	{"entity.firework_rocket.large_blast", 1, v_FIREWORK_LARGE_BLAST},
	{"entity.firework_rocket.twinkle", 1, v_FIREWORK_TWINKLE},
	{"entity.item.pickup", 1, v_ITEM_PICKUP},
	{"entity.item.break", 1, v_ITEM_BREAK},
	{"item.totem.use", 1, v_TOTEM_USE},
	{"entity.arrow.shoot", 1, v_ARROW_SHOOT},
	{"entity.arrow.hit", 4, v_ARROW_HIT},
	{"entity.arrow.hit_player", 1, v_ARROW_HIT_PLAYER},
	{"item.crossbow.loading_middle", 10, v_BOW_PULL},
	{"entity.generic.explode", 4, v_EXPLODE},
	{"entity.tnt.primed", 1, v_TNT_PRIMED},
	{"entity.zombie.hurt", 2, v_ZOMBIE_HURT},
	{"entity.zombie.death", 1, v_ZOMBIE_DEATH},
	{"ui.button.click", 1, v_UI_CLICK},
	{"entity.lightning_bolt.thunder", 3, v_THUNDER},
	{"block.wooden_door.open", 2, v_DOOR_WOOD_OPEN},
	{"block.wooden_door.close", 3, v_DOOR_WOOD_CLOSE},
	{"block.iron_door.open", 4, v_DOOR_IRON_OPEN},
	{"block.iron_door.close", 4, v_DOOR_IRON_CLOSE},
	{"block.chest.open", 1, v_CHEST_OPEN},
	{"block.note_block.pling", 1, v_NOTE_PLING},
	{"block.anvil.land", 1, v_ANVIL_LAND},
	{"entity.creeper.primed", 1, v_CREEPER_PRIMED},
	{"entity.creeper.hurt", 4, v_CREEPER_HURT},
	{"entity.creeper.death", 1, v_CREEPER_DEATH},
	{"entity.husk.hurt", 2, v_HUSK_HURT},
	{"entity.husk.death", 2, v_HUSK_DEATH},
	{"entity.drowned.hurt", 3, v_DROWNED_HURT},
	{"entity.drowned.death", 2, v_DROWNED_DEATH},
	{"ui.toast.in", 1, v_TOAST_IN},
	{"ui.toast.challenge_complete", 1, v_TOAST_CHALLENGE},
	{"entity.enderman.hurt", 4, v_ENDERMAN_HURT},
	{"entity.enderman.death", 1, v_ENDERMAN_DEATH},
	{"entity.enderman.teleport", 2, v_ENDERMAN_TELEPORT},
	{"entity.enderman.stare", 1, v_ENDERMAN_STARE},
	{"block.lever.click", 1, v_LEVER_CLICK},
	{"block.stone_button.click_on", 1, v_STONE_BUTTON_ON},
	{"block.stone_button.click_off", 1, v_STONE_BUTTON_OFF},
	{"block.wooden_button.click_on", 1, v_WOOD_BUTTON_ON},
	{"block.wooden_button.click_off", 1, v_WOOD_BUTTON_OFF},
	{"block.stone_pressure_plate.click_on", 1, v_STONE_PLATE_ON},
	{"block.stone_pressure_plate.click_off", 1, v_STONE_PLATE_OFF},
	{"block.wooden_pressure_plate.click_on", 1, v_WOOD_PLATE_ON},
	{"block.wooden_pressure_plate.click_off", 1, v_WOOD_PLATE_OFF},
	{"item.crossbow.loading_start", 1, v_CROSSBOW_LOAD_START},
	{"item.crossbow.loading_end", 1, v_CROSSBOW_LOAD_END},
	{"item.crossbow.shoot", 9, v_CROSSBOW_SHOOT},
	{"item.flintandsteel.use", 1, v_FLINT_USE},
	{"block.fire.ambient", 1, v_FIRE_AMBIENT},
	{"entity.player.hurt_on_fire", 3, v_PLAYER_HURT_FIRE},
	{"block.enchantment_table.use", 3, v_ENCHANT},
	{"entity.iron_golem.attack", 1, v_IRON_GOLEM_ATTACK},
	{"entity.iron_golem.hurt", 4, v_IRON_GOLEM_HURT},
	{"entity.iron_golem.death", 1, v_IRON_GOLEM_DEATH},
	{"entity.iron_golem.step", 4, v_IRON_GOLEM_STEP},
	{"entity.wither.spawn", 1, v_WITHER_SPAWN},
	{"entity.wither.ambient", 4, v_WITHER_AMBIENT},
	{"entity.wither.shoot", 1, v_WITHER_SHOOT},
	{"entity.wither.hurt", 4, v_WITHER_HURT},
	{"entity.wither.death", 1, v_WITHER_DEATH},
	{"entity.wither.break_block", 1, v_WITHER_BREAK_BLOCK},
	{"block.stone.break", 4, v_STONE_BREAK},
	{"block.stone.hit", 6, v_STONE_HIT},
	{"block.stone.place", 4, v_STONE_PLACE},
	{"block.stone.step", 6, v_STONE_STEP},
	{"block.wood.break", 4, v_WOOD_BREAK},
	{"block.wood.hit", 6, v_WOOD_HIT},
	{"block.wood.place", 4, v_WOOD_PLACE},
	{"block.wood.step", 6, v_WOOD_STEP},
	{"block.sand.break", 4, v_SAND_BREAK},
	{"block.sand.hit", 5, v_SAND_HIT},
	{"block.sand.place", 4, v_SAND_PLACE},
	{"block.sand.step", 5, v_SAND_STEP},
	{"block.gravel.break", 4, v_GRAVEL_BREAK},
	{"block.gravel.hit", 4, v_GRAVEL_HIT},
	{"block.gravel.place", 4, v_GRAVEL_PLACE},
	{"block.gravel.step", 4, v_GRAVEL_STEP},
	{"block.grass.break", 4, v_GRASS_BREAK},
	{"block.grass.hit", 6, v_GRASS_HIT},
	{"block.grass.place", 4, v_GRASS_PLACE},
	{"block.grass.step", 6, v_GRASS_STEP},
	{"block.glass.break", 3, v_GLASS_BREAK},
	{"block.glass.hit", 6, v_GLASS_HIT},
	{"block.glass.place", 4, v_GLASS_PLACE},
	{"block.glass.step", 6, v_GLASS_STEP},
	{"block.metal.break", 4, v_METAL_BREAK},
	{"block.metal.hit", 6, v_METAL_HIT},
	{"block.metal.place", 4, v_METAL_PLACE},
	{"block.metal.step", 6, v_METAL_STEP},
	{"block.wool.break", 4, v_WOOL_BREAK},
	{"block.wool.hit", 4, v_WOOL_HIT},
	{"block.wool.place", 4, v_WOOL_PLACE},
	{"block.wool.step", 4, v_WOOL_STEP},
};
} // namespace mcs
